server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.226.132
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.226.132
ly:
  sms:
    accessKeyId: LTAIf5vJTEe70iPa
    accessKeySecret: A2ZGBWfrkz9arF908cmDWXmIrAlngA
    signName: 乐优商城
    verifyCodeTemplate: SMS_133976814